### ISSUE TITLE
Widget support

### ISSUE THREAD

**Issue by Radiergummi** [workingconcept/cloudflare-craft-plugin#1]
Hey there, the plugin works like a charm, thanks. What'd be your opinion on creating a dashboard widget to quickly purge the cloudflare cache?

**Comment by mattstein** [comment]
Seems like a great idea! I'll look into it when I have some extra time.

**Comment by Radiergummi** [comment]
Awesome! I've got some free time on my hands currently, so I'll see if I can come up with a PR.

**Comment by mattstein** [comment]
That'd be kind of you, and I'd be happy to take a look at it.

**Comment by mattstein** [comment]
🎉
