### ISSUE TITLE
Can't verify credentials, but they work

### ISSUE THREAD

**Issue by jkorff** [workingconcept/cloudflare-craft-plugin#10]
After adding my API key and account email and clicking on 'Verify Credentials' the plugin says "Could not verify API credentials". 

But they work as when I navigate away and back to the settings the Cloudflare zones are shown correctly, and I can successfully purge individual URLs manually.

However, auto-purging does not work at all.

I couldn't find any entries of this plugin in Craft's web.log.

Can you guide me towards a resolution of this issue? Thank you.

Craft 3.0.36 | PHP 7.2.13 | Plugin 0.2.3

**Comment by mattstein** [comment]
Thanks for reporting this, @jkorff! I can reproduce this, so I'll get it fixed and give you a shout.

**Comment by mattstein** [comment]
I just cleaned up a whole bunch of things and published [a new version](https://github.com/workingconcept/cloudflare-craft-plugin/releases/tag/0.2.4), @jkorff.

> After adding my API key and account email and clicking on 'Verify Credentials' the plugin says "Could not verify API credentials".

My apologies, the AJAX was broken with a change made in 0.2.2. Definitely fixed.

> I couldn't find any entries of this plugin in Craft's web.log.

I updated all logging that used the (deprecated) `Craft::trace`, so logs should be way more useful now when you search for them for `[cloudflare]`.

> However, auto-purging does not work at all.

Auto-purging of Entry and Asset URLs _is_ working for me with respect to the settings. Give this version a try, and I'd be happy to help if the logs still aren't giving you anything useful! Keep in mind that if your Entry or Asset URLs aren't on the zone Cloudflare won't be able to purge them.

**Comment by jkorff** [comment]
You're on fire! Thank you for the update. I have updated my version and... got a server 500 error, because there's a trailing comma in CloudflareService.php on line 268.

Once removed, the plugin works as expected, including the auto-purging of entries. Nice! Thank you.

**Comment by mattstein** [comment]
Oh okay, so _no_ on the trailing comma then. ;)

Thanks for promptly identifying the source of my embarrassment @jkorff! Fixed in [0.2.5](https://github.com/workingconcept/cloudflare-craft-plugin/releases/tag/0.2.5).

**Comment by jkorff** [comment]
Thank you!

**Comment by mattstein** [comment]
Just FYI, I posted yet another release to fix a console exception. Hopefully three will be enough for today.

**Comment by jkorff** [comment]
I believe so, Matt! Thank you. I'm glad your plugin exists. It's very well documented, that's why I picked it over others.

**Comment by jayhlee** [comment]
I'm having a similar issue when trying to "Verify Credentials." I get an error message under the `Cloudflare Zone ID` that reads "Warning:Unable to list zones for selection. You must specify a Zone ID." I'm certain the Zone ID is correct because I'm using the same ID with Blitz. 

Not sure if it helps to diagnose what's going on, but my logs show the following error:

`Request failed: {"success":false,"errors":[{"code":9103,"message":"Unknown X-Auth-Key or X-Auth-Email"}],"messages":[],"result":null}`

**Comment by mattstein** [comment]
@jayhlee Assuming you’re using an API token, can you share how the relevant token is configured? (Without the secret itself, obviously.)

If the Cloudflare plugin doesn’t think it can list zones for you to select one, it’ll prompt for an explicit zone ID. That _should_ still be working as it is with Blitz, despite the change in UI because of the token’s limited permissions.

**Comment by jayhlee** [comment]
I'm just using the API Key for authentication. The API Key, CF email, and Zone ID are entered and are correct. They're the same values I'm using with Blitz.

**Comment by mattstein** [comment]
I’m not sure how that’s possible, @jayhlee. Just did a quick test with my Cloudflare email address and “Global API Key” which worked as expected. (Entered the email address directly and the key as an environment variable.)

Pressed **Verify Credentials** and got a green check mark along with a complete list of zones without any error message. Saved fine as well.

That error message [makes it _look_ like](https://community.cloudflare.com/t/unknown-x-auth-key-or-x-auth-email/76406) the credentials are wrong, but if they’re working with Blitz then I’m stumped.

**Comment by jayhlee** [comment]
I just removed and re-added the site on Cloudlflare and added the new credentials. Everything seems to now work. Really weird! 

Thanks for your help! Not sure what the issue was. But as long as everything works, I'm good!

**Comment by mattstein** [comment]
Maybe a clog in the tubes somewhere? Glad it’s working again!
