### ISSUE TITLE
[Feature Request] Do Not Display API Key

### ISSUE THREAD

**Issue by mattcdavis1** [workingconcept/cloudflare-craft-plugin#11]
Cloudlflare unfortunately does not have functionality (at least up through the business plan) to limit the access of an API key.  That means any CMS user that can view the API key in the CMS has full access to the Cloudflare account via the API.  

Hopefully Cloudflare will allow more granular control in the future, but in the meantime i think the API key should be write-only similar to how passwords are handled.  A CMS user should only be able to update an API key but not see the existing key.

**Comment by mattstein** [comment]
Thanks for opening an issue, @mattcdavis1! Why don't I just add support for environment variables in the configuration? (Not sure if you've seen this, but it's nice and I think it would solve the problem: https://docs.craftcms.com/v3/config/environments.html#control-panel-settings.)

**Comment by mattstein** [comment]
Not obvious from the documentation is that secrets are obfuscated in that dropdown, so the key still wouldn't be exposed. Here's a screenshot from another plugin:

<img width="583" alt="screen shot 2019-02-26 at 9 53 31 am" src="https://user-images.githubusercontent.com/2488775/53434962-8892f000-39ac-11e9-915a-3e2f2f42a2a1.png">

**Comment by mattcdavis1** [comment]
Yeah - i think an env value option would be great!

**Comment by mattstein** [comment]
Just added in [a new release](https://github.com/workingconcept/cloudflare-craft-plugin/releases/tag/0.2.7), @mattcdavis1. Thanks again for the suggestion.

**Comment by mattcdavis1** [comment]
great - thanks!
