### ISSUE TITLE
"aws-s3" plugin compatibility

### ISSUE THREAD

**Issue by Rayduxz** [workingconcept/cloudflare-craft-plugin#12]
When using the "aws-s3" plugin, you can set a custom domain for an Amazon S3 bucket by using the "Static website hosting" option and configuring it correctly.

So let's say we have our site under the domain "example.com".
I have configured an S3 Asset Volume with the Base URL as the subdomain "assets.example.com".

![image](https://user-images.githubusercontent.com/9803377/54828459-f9b78180-4c92-11e9-8430-bca9200906b2.png)

When the Cloudflare plugin purges the assets caches, it should detect if there is a Volume with the Base URL in the same Zone ID as the main domain so it can work for any subdomain.

**Comment by mattstein** [comment]
@Rayduxz I just published [0.2.9](https://github.com/workingconcept/cloudflare-craft-plugin/releases/tag/0.2.9), which should now purge whatever subdomains you request provided they're on the same zone you've configured the plugin to use.

Closing this out, but let me know if you try it and have any issues!
