### ISSUE TITLE
Multi-site support?

### ISSUE THREAD

**Issue by jishi** [workingconcept/cloudflare-craft-plugin#13]
I'm trying to figure out if this plugin has multi-site support from the documentation, but my understanding is that it doesn't?

Example: Having a single CMS installation that serves both `a-domain.com` and `b-domain.com` and when editing content purging both of them (or preferably just the one you are editing). 

Seems like it supports subdomain purging automatically (does it just purge all cache under the same domain?), but you can only specify a single zone ID the config, hence making it impossible to act on multiple zones?

Thanks in advance, Jimmy

**Comment by mattstein** [comment]
Hey @jishi, you're right that the plugin currently supports setting a single zone. It'll attempt to clear URLs matching the zone's domain name, so while it'd be fine with several subdomains it's limited to one primary/root domain.

I'm not sure when I can get to this, but it'd be a great to support however many sites/domains a Craft install might use.

**Comment by jishi** [comment]
Cool, thanks for the response. Maybe I'll look into it when the time comes and use your plugin as reference. If I get it to work I'll give you a PR for you to evaluate if you want to bring it into this plugin.

**Comment by toddpadwick** [comment]
Hi @jishi 
Im running into this requirement myself. Did you find a solution? even a temporary one will be helpful.

**Comment by adrienne** [comment]
@mattstein did this ever end up getting multi-site support?

**Comment by mattstein** [comment]
@adrienne No it did not. Would be a great feature, but I’m not sure when I’d get around to it.

**Comment by kerrig** [comment]
I know this is old but just pointing out that I'm running into this issue with a client site and would love for this functionality as well.

**Comment by boboldehampsink** [comment]
@bencroker it would be nice to have multisite support, like the blitz cloudflare purger has
