### ISSUE TITLE
Craft Commerce support

### ISSUE THREAD

**Issue by oddnavy** [workingconcept/cloudflare-craft-plugin#16]
It would be amazing if this plugin supported Craft Commerce products 😄

**Comment by mattstein** [comment]
Hmm, or maybe any Element with its own URL. 🤔

Thanks for the suggestion, @oddnavy!

**Comment by mattstein** [comment]
FWIW I’ve added a feature branch for this and it’s working nicely! Just need a real migration and a bit more testing.

<img width="563" alt="automatic-purge" src="https://user-images.githubusercontent.com/2488775/76235804-a159f680-61f9-11ea-87ef-f2b7295d45bc.png">

**Comment by oddnavy** [comment]
@mattstein nice work! That will be a great addition.

We're using the element-api for a site I'm working as the site is headless. Is there a way to configure a rule for clearing an element-api endpoint at the same time as the frontend endpoint?

For example: on save of product id 2, purge `cms.site.dev/api/products/2` + `site.dev/product/2`

**Comment by mattstein** [comment]
There isn’t currently a way to do that @oddnavy—but you’re limited to one interesting idea per issue! 😄

**Comment by mattstein** [comment]
Finally added in [0.5.0](https://github.com/workingconcept/cloudflare-craft-plugin/releases/tag/0.5.0).
