### ISSUE TITLE
"Zone cannot be blank" when trying to save plugin settings

### ISSUE THREAD

**Issue by benface** [workingconcept/cloudflare-craft-plugin#19]
Hey Matt! I believe [this commit](https://github.com/workingconcept/cloudflare-craft-plugin/commit/f9719fb88fd1fe50f6656a60ea83b65b09ecde14) introduced a bug that prevents selecting a zone with an API key that *does* list zones. Basically when I try to save the plugin settings for the first time with every field filled in (and a zone selected in the "Cloudflare Zone" select), I get the error message "Zone cannot be blank" (weirdly I get it in two places: below the "Cloudflare Zone" field, and below "Authentication Type" as well). I checked the HTML and I believe it's because there are two form elements with the same `settings[zone]` name: a `<select>` and an `<input>`. The latter is invisible but its empty value overrides whatever value the former has since it appears later in the HTML.

**Comment by mattstein** [comment]
Well that’s some lackluster front end material then. Thanks for pointing that out Benoît, I’ll get it fixed!

**Comment by mattstein** [comment]
Just fixed in [0.5.1](https://github.com/workingconcept/cloudflare-craft-plugin/releases/tag/0.5.1)!
