### ISSUE TITLE
Multi-level domain suffixes throw errors when purging URLs

### ISSUE THREAD

**Issue by kswilliames** [workingconcept/cloudflare-craft-plugin#22]
When purging an entry URL on save or a specific URL from the dashboard widget, I'm encountering an "Invalid URL" error.

It is throwing on zones with domains that are more than one level eg. `www.example.org.au/path/to/something`. The [URLHelper](https://github.com/workingconcept/cloudflare-craft-plugin/blob/5d1cdf8d818336f8bc2a27139e48131caba8d81a/src/helpers/UrlHelper.php#L100) is cutting these URLs down to 'org.au' and comparing that to the registrable domain 'example.org.au', which always fails the `isPurgeableUrl` check.

The most reliable way of determining the registrable domain is by using the Public Suffix List. I've made a pull request with a plugin that extracts domains using a cached public list.

Thanks for a great plugin!

**Comment by gbowne-quickbase** [comment]
I am seeing similar behavior when trying to purge `www.example.com/path/to/something` and but the Plugin throws a `Ignoring URL outside zone` error. 
Looking into it, the comparison between the $urlDomain and the $cfDomainName provided by the [UrlHelper](https://github.com/workingconcept/cloudflare-craft-plugin/blob/2e002c484af16db811301dd6c3c86d199c5f3a0e/src/helpers/UrlHelper.php#L79) yields a comparison between `example.com` and `www.example.com` (from my Zone) which never match.

If I essentially ignore that check, my purges go through perfectly.

**Comment by mattstein** [comment]
Just released [v1.0.0](https://github.com/workingconcept/cloudflare-craft-plugin/releases/tag/1.0.0) with an update for this.
