### ISSUE TITLE
Unhide the /cloudflare/rules section

### ISSUE THREAD

**Issue by gbowne-quickbase** [workingconcept/cloudflare-craft-plugin#26]
If I hadn't tripped over it in the docs, I'd never have found it. Can you make it a tab on the Plugin config section?

**Comment by mattstein** [comment]
That feature’s about as bold as the version number on this project. I’ve been meaning to revamp the settings and give the rules table a proper home in a 1.0 release—will leave this open until that’s done.

**Comment by gbowne-quickbase** [comment]
That's totally fair! We/re moving off Ak*mai to Cloudflare, so I'm eager to make things easy for my team

**Comment by RichardDillman** [comment]
This section is really helpful, so +1 for exposing it.
I wonder if we could get a pattern that triggers a pattern.  I have an AMP version of all my articles.  Would be pretty awesome if `/articles/{slug}` could also trigger their matching `/amp/articles{slug}`.

**Comment by mattstein** [comment]
Finally released [v1.0.0](https://github.com/workingconcept/cloudflare-craft-plugin/releases/tag/1.0.0) with this update.
