### ISSUE TITLE
Deprecation warning about composer upgrade

### ISSUE THREAD

**Issue by gbowne-quickbase** [workingconcept/cloudflare-craft-plugin#28]
I just wanted to let you know about this upcoming deprecation issue. I think it's easily fixed by changing the name/casing of the file to comply with `psr-4` standards:

`Deprecation Notice: Class workingconcept\cloudflare\assetbundles\Cloudflare\CloudflareAsset located in ./vendor/workingconcept/craft-cloudflare/src/assetbundles/cloudflare/CloudflareAsset.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/Cellar/composer/1.9.3/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201`

**Comment by mattstein** [comment]
Thanks for the reminder, @gbowne-quickbase! I’ve been meaning to fix that.
