### ISSUE TITLE
Craft 3

### ISSUE THREAD

**Issue by Radiergummi** [workingconcept/cloudflare-craft-plugin#3]
Hey it's me, bothering you again 😄   
I've not yet read too much on migrating plugins to Craft 3, but it looks like it'll be a lot of work. Any chance on an update? I'd be willing to contribute some of my company time into developing a compatible version, too.

**Comment by mattstein** [comment]
Why hello again, @Radiergummi! I suppose I should get this updated for Craft 3, so let's call that an official plan. I'll keep this issue open so you know when to find all my bugs. :)

**Comment by mattstein** [comment]
Done in e78a2cfe451d74a2cff71af84be091f8eaf23886. 🎉
