### ISSUE TITLE
Zone ID behaviour

### ISSUE THREAD

**Issue by meestaben** [workingconcept/cloudflare-craft-plugin#30]
Hi,

We have two Cloudflare accounts - one for production, and one for non-production sites (each having a single Zone), so we don't want zone IDs being stored in project.yaml. My understanding is that if the plugin isn't able to retrieve a list of zones, it assumes you want to specify the ID manually rather than choosing from a list. However, despite my Cloudflare API Token having _only_ the Cache Purge permission and not the Zone Read permission, the 'zones' API call still returns a list of zones, so the dropdown is always shown instead of the input box. 

![Screenshot 2021-01-07 at 15 31 53](https://user-images.githubusercontent.com/15892203/103914536-df69c480-5101-11eb-9204-aa234392a6a7.png)

If I change the Zone Resources option to Exclude all zones from the account, then the plugin does display the input box instead of the dropdown, but then I'm obviously unable to perform any cache purge operations.

Ideally the plugin would allow me to tick a checkbox called "Specify Zone ID manually" which would grey out the dropdown and show the input field, allowing me to use an env var rather than trying to second-guess based on whether the API allows zones to be enumerated or not.

**Comment by mattstein** [comment]
Hi @meestaben,

You should be able to solve this problem by setting your zone ID to an environment variable in a static config file.

**config/cloudflare.php**

```php
<?php

return [
	'apiToken' => '$CLOUDFLARE_API_TOKEN',
    'zone' => '$CLOUDFLARE_ZONE_ID'
];
```

You can then set `CLOUDFLARE_API_TOKEN` and `CLOUDFLARE_ZONE_ID` in each environment to keep the values out of project config while skipping the control panel settings UI to manually designate a token.

**Comment by meestaben** [comment]
Awesome @mattstein, thanks for the clarification, and thanks also for creating this plugin!  👍
