### ISSUE TITLE
PDP attempts to write to the vendor folder during cache purges

### ISSUE THREAD

**Issue by mattgrayisok** [workingconcept/cloudflare-craft-plugin#31]
Currently PDP is being instantiated with default cache settings which is causing it to try to use the vendor folder as a cache directory. As it is generally best practice for the vendor folder to not be writable by the PHP user (other than during the installation process) this causes some issues when the vendor folder isn't writable. Specifically:

```
2021-02-02 11:17:34 [-][8596][64d388c3db444aaed528eb691057f9b5][error][InvalidArgumentException] InvalidArgumentException: cache path does not exist or is not writable: /var/www/html/vendor/jeremykendall/php-domain-parser/data in /var/www/html/vendor/jeremykendall/php-domain-parser/src/Cache.php:94
```

The PDP Cache class accepts a cache path as a parameter:

https://github.com/jeremykendall/php-domain-parser/blob/00000757d769931e876f9f6607b93c3db3464616/src/Cache.php#L82

This could be set to Craft's runtime cache directory in order to avoid the issue, and also it just feels nicer:

https://github.com/workingconcept/cloudflare-craft-plugin/blob/2048e6ac7725d7162f32288db4be6cf10296780f/src/helpers/UrlHelper.php#L99

Thanks 💪

**Comment by mattstein** [comment]
Good idea, thanks @mattgrayisok! I’ll get this into a new release as soon as I can.

**Comment by mattstein** [comment]
Just tagged [1.0.1](https://github.com/workingconcept/cloudflare-craft-plugin/releases/tag/1.0.1) which should do the trick!
