### ISSUE TITLE
Trying to get property 'id' of non-object

### ISSUE THREAD

**Issue by justenh** [workingconcept/cloudflare-craft-plugin#44]
Hi,

We recently rolled this plugin out to our website running `Craft Pro 3.7.27.2` and are receiving the following error when updating assets. It appears that the asset saves, but the error is triggered.

```
PHP Notice – yii\base\ErrorException
Trying to get property 'id' of non-object
```
<img width="1532" alt="Screen Shot 2022-01-25 at 7 11 02 PM" src="https://user-images.githubusercontent.com/3868091/151086517-b37705dd-885c-494f-9480-876e60988287.png">

Thanks for the great plugin, and your help!

**Comment by mattstein** [comment]
Thanks for pointing this out, @justenh! Seeing the same thing on Craft 3.7.29, specifically when Cloudflare’s API returns a 200 response but the purge itself failed. So there’s still an underlying issue to investigate—in my case a purge request for a domain outside the Cloudflare zone—but whatever the issue it’ll be exposed in Craft’s logs rather than resulting in a big loud exception like this.

You can try this out now if you’d like to require the `develop` branch in `composer.json`:

```json
"workingconcept/craft-cloudflare": "dev-develop as 1.0.3",
```

**Comment by justenh** [comment]
@mattstein  Thanks. That makes sense. We have a volume of assets that are not controlled by the same Cloudflare zone. This is most likely where the error occurred.

**Comment by mattstein** [comment]
[1.0.3](https://github.com/workingconcept/cloudflare-craft-plugin/releases/tag/1.0.3) is out now with this change.

**Comment by justenh** [comment]
@mattstein  Thank you for the update. We've deployed the latest version `1.0.3` (confirmed via System Report), However, we are seeing that the issue is still present when saving an asset. Anything in particular I can look into to help resolve?

**Comment by justenh** [comment]
@mattstein The update (0405810 ) looks like it might miss the issue. The issue being displayed is `Trying to get property 'id' of non-object` related to line 343 in `services/Api` where the call to `Craft::info` is attempting to record the results of the purged URL using `$responseBody->result->id` - In our case, after any asset is saved/modified.

**Comment by mattstein** [comment]
Oof. 🤦‍♂️ 

Thanks @justenh, I’ll get this fixed for each case where this could be an issue—instead of _only_ the wrong one for the situation you reported.

**Comment by mattstein** [comment]
Alright @justenh, [1.0.3.1](https://github.com/workingconcept/cloudflare-craft-plugin/releases/tag/1.0.3.1) should do it.

**Comment by justenh** [comment]
@mattstein I can confirm that the latest release no longer triggers the exception. Thanks!
