### ISSUE TITLE
Duplicating Element Count 

### ISSUE THREAD

**Issue by ljclark** [workingconcept/cloudflare-craft-plugin#5]
Seems to be a bug/conflict between the CP Element Count Plugin from aelvan (https://github.com/aelvan/craft-cp-element-count/blob/master/README.md) and this one - having these two enabled at the same time is causing duplicate element counts in the CMS - see screenshot. 

If you disable the cloudfare plugin, it removes the issue. No errors in the console though. 

![screen shot 2018-05-09 at 08 21 05](https://user-images.githubusercontent.com/8060816/39801321-b195fb0e-5362-11e8-9f99-de9193af8569.png)

**Versions**

CP Element Count: 1.0.0
Cloudfare: 0.2.0
Craft: C3.0.5

**Comment by ljclark** [comment]
This actually looks to have been resovled on my end by updating to C3.0.6 - just for reference incase any one else gets this issue.

**Comment by mattstein** [comment]
Thanks for reporting @ljclark! I'll happily blame Craft for now and dig in if this rears its head again. :)
