### ISSUE TITLE
Element-based tracking and purging of URLs

### ISSUE THREAD

**Issue by khalwat** [workingconcept/cloudflare-craft-plugin#53]
Have you given thought to using Craft's new-ish built-in functionality for collecting element cache tags via `Elements::startCollectingCacheTags()` / `Elements::stopCollectingCacheTags()` to get a list of tag dependencies for a rendered template, so that you could automatically purge the appropriate URLs without having to list rules?

**Comment by mattstein** [comment]
Hadn’t, but suppose I should—thank you!

**Comment by khalwat** [comment]
You potentially open to a PR on this matter?

**Comment by mattstein** [comment]
I'd be honored!

**Comment by khalwat** [comment]
Related Craft PR: https://github.com/craftcms/cms/pull/11617

**Comment by bencroker** [comment]
Thanks for the suggestion @khalwat. For the meantime, tracking element changes is beyond the scope of this plugin.
