### ISSUE TITLE
Documentation shows old config settings

### ISSUE THREAD

**Issue by mike-moreau** [workingconcept/cloudflare-craft-plugin#63]
In reviewing the plugin documentation here https://putyourlightson.com/plugins/cloudflare#zone-permissions, it looks like references to `purgeEntryUrls` and `purgeAssetUrls` need to be updated to the current `purgeElements`.

Thanks for the plugin!

**Comment by bencroker** [comment]
Thanks for reporting! Have fixed the docs. Apologies for the delay in responding, it turns out I had notifications disabled on this repo.

**Comment by mike-moreau** [comment]
Thank you!
