### ISSUE TITLE
Craft 4 installation

### ISSUE THREAD

**Issue by franck-agencehoffman** [workingconcept/cloudflare-craft-plugin#64]
I try to install the plugin on Craft CMS 4 on any project I am getting this error when trying install it.

`./craft plugin/install cloudflare
*** installing cloudflare
Exception: Cannot assign null to property putyourlightson\cloudflare\migrations\Install::$driver of type string (/Users/franckjorge/Desktop/Workspace/energir/vendor/putyourlightson/craft-cloudflare/src/migrations/Install.php:26)
#0 /Users/franckjorge/Desktop/Workspace/energir/vendor/craftcms/cms/src/db/Migration.php(49): putyourlightson\cloudflare\migrations\Install->safeUp()
#1 /Users/franckjorge/Desktop/Workspace/energir/vendor/craftcms/cms/src/db/MigrationManager.php(233): craft\db\Migration->up(true)
#2 /Users/franckjorge/Desktop/Workspace/energir/vendor/craftcms/cms/src/base/Plugin.php(144): craft\db\MigrationManager->migrateUp(Object(putyourlightson\cloudflare\migrations\Install))
#3 /Users/franckjorge/Desktop/Workspace/energir/vendor/craftcms/cms/src/services/Plugins.php(532): craft\base\Plugin->install()
#4 /Users/franckjorge/Desktop/Workspace/energir/vendor/craftcms/cms/src/console/controllers/PluginController.php(281): craft\services\Plugins->installPlugin('cloudflare')
#5 /Users/franckjorge/Desktop/Workspace/energir/vendor/craftcms/cms/src/console/controllers/PluginController.php(143): craft\console\controllers\PluginController->_installPluginByHandle('cloudflare')
#6 [internal function]: craft\console\controllers\PluginController->actionInstall('cloudflare')
#7 /Users/franckjorge/Desktop/Workspace/energir/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#8 /Users/franckjorge/Desktop/Workspace/energir/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#9 /Users/franckjorge/Desktop/Workspace/energir/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('install', Array)
#10 /Users/franckjorge/Desktop/Workspace/energir/vendor/craftcms/cms/src/console/ControllerTrait.php(87): yii\console\Controller->runAction('install', Array)
#11 /Users/franckjorge/Desktop/Workspace/energir/vendor/craftcms/cms/src/console/Controller.php(217): craft\console\Controller->traitRunAction('install', Array)
#12 /Users/franckjorge/Desktop/Workspace/energir/vendor/yiisoft/yii2/base/Module.php(552): craft\console\Controller->runAction('install', Array)
#13 /Users/franckjorge/Desktop/Workspace/energir/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('plugin/install', Array)
#14 /Users/franckjorge/Desktop/Workspace/energir/vendor/craftcms/cms/src/console/Application.php(90): yii\console\Application->runAction('plugin/install', Array)
#15 /Users/franckjorge/Desktop/Workspace/energir/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('plugin/install', Array)
#16 /Users/franckjorge/Desktop/Workspace/energir/vendor/craftcms/cms/src/console/Application.php(121): yii\console\Application->handleRequest(Object(craft\console\Request))
#17 /Users/franckjorge/Desktop/Workspace/energir/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
#18 /Users/franckjorge/Desktop/Workspace/energir/craft(22): yii\base\Application->run()
#19 {main}
*** failed to install cloudflare: An error occurred while executing the "putyourlightson\cloudflare\migrations\Install migration: Cannot assign null to property putyourlightson\cloudflare\migrations\Install::$driver of type string`

**Comment by bencroker** [comment]
Thanks for reporting! Fixed in https://github.com/putyourlightson/craft-cloudflare/commit/24b13d72813c58adcd8c6ac487217545666e24ae. Apologies for the delay in responding, it turns out I had notifications disabled for this repo.

**Comment by bencroker** [comment]
Released in version [2.0.1](https://github.com/putyourlightson/craft-cloudflare/releases/tag/2.0.1).
