### ISSUE TITLE
Does not return full list of Zones

### ISSUE THREAD

**Issue by HhebertGhost** [workingconcept/cloudflare-craft-plugin#65]
There is a bug in [services/Api.php](https://github.com/putyourlightson/craft-cloudflare/blob/v2/src/services/Api.php#L378) that means that the plugin cannot return more than the first 50 zones. The issue comes from the pages attribute not being specified in the request.

**Comment by bencroker** [comment]
Thanks for reporting! Fixed in https://github.com/putyourlightson/craft-cloudflare/commit/db3079d24911ca7035dea1ab3d2ec9048be7778d. Apologies for the delay in responding, it turns out I had notifications disabled for this repo.

**Comment by bencroker** [comment]
Released in version [2.0.1](https://github.com/putyourlightson/craft-cloudflare/releases/tag/2.0.1).
