### ISSUE TITLE
Documentation error: Purge Rules

### ISSUE THREAD

**Issue by Diewy** [workingconcept/cloudflare-craft-plugin#68]
In the documentation of the Plugin there is reference to a "cloudflare/rules" page, but it isn't available. It seems like the functionality got moved to the utility.

See: https://putyourlightson.com/plugins/cloudflare#purge-rules

When trying to visit the page I saw there is indeed a [CP URL registered](https://github.com/putyourlightson/craft-cloudflare/blob/develop/src/Cloudflare.php#L184), but the template doesn't exist.

**Comment by bencroker** [comment]
Thanks for reporting this! Fixed at https://putyourlightson.com/plugins/cloudflare#purge-rules
