### ISSUE TITLE
Gateway timeout on settings page

### ISSUE THREAD

**Issue by MadMikeyB** [workingconcept/cloudflare-craft-plugin#69]
When I go to Settings and click the CloudFlare icon under Plugins, the page attempts to load and then times out with a Gateway Timeout (504 nginx).

```
2024/03/18 10:26:27 [error] 39565#11553564: *11792 upstream timed out (60: Operation timed out) while reading response header from upstream, client: 127.0.0.1, server: craft.test, request: "GET /admin/settings/plugins/cloudflare?site=main HTTP/2.0", upstream: "fastcgi://unix:/Users/mikey/Library/Application Support/Herd/herd.sock", host: "craft.test", referrer: "https://craft.test/admin/settings?site=main"
```

This happens both on my local environment and on production environments.

I have updated to the latest version of Craft and Plugin.

I have attempted uninstalling the plugin and re-installing, to no avail.

It does not happen on a fresh craft install with no saved credentials.

I can only assume there's some bad settings saved somewhere - and an uninstall/reinstall didn't clear them out as I had hoped. Any way to remove bad settings from the database / catch the timeout in the code where any api call is made?

I have looked in here https://github.com/putyourlightson/craft-cloudflare/blob/develop/src/templates/settings.twig but cannot see it making an API call unless the javascript bridge is doing that.

**Comment by MadMikeyB** [comment]
Deleting config/cloudflare.php solved the issue. It was pointing to an environment variable that did not exist, this seems to have broken the whole page causing it to timeout. Perhaps an empty check on the environment variables could solve this in the future?

**Comment by bencroker** [comment]
Glad to hear you figured it out! Can you show me an example of “pointing to an environment variable that did not exist”, so I can replicate this locally?

**Comment by bencroker** [comment]
Closed due to inactivity.
