### ISSUE TITLE
Having trouble using the api purgeUrls() service.

### ISSUE THREAD

**Issue by thisanimus** [workingconcept/cloudflare-craft-plugin#70]
I'm having trouble getting the purgeUrls() service to work via an event hook.  

I have tried accessing it directly: 

```php
...
use putyourlightson\cloudflare\Cloudflare;

class AnnouncementServices extends Component {
	...
	public function processSave($entry) {

		$related = $entry->related->all();
		$urls = [];
		foreach ($related as $entry) {
			$urls[] = $entry->url;
		}
		Cloudflare::$plugin->api->purgeUrls($urls);
	}
	...
}
```

And also via the queue:

```php
...
use putyourlightson\cloudflare\queue\jobs\PurgeCloudflareCache;

class AnnouncementServices extends Component {
	...
	public function processSave($entry) {

		$related = $entry->related->all();
		$urls = [];
		foreach ($related as $entry) {
			$urls[] = $entry->url;
		}
		Queue::push(new PurgeCloudflareCache([
			'urls' => $urls
		]));
	}
	...
}
```
When I dump the `$urls` array, the urls that need to be purged are in fact present in the array.

Both seem to run just fine, but the CF cache remains un-purged.

Purging cache on the entry being saved, and via the plugin control panel does work.

Am I using the service incorrectly?  Do you have any guidance on how to correctly use it?

**Comment by bencroker** [comment]
Both of those should work. Can you try outputting the response result to see whether there is an error?

```php
\Craft::dd(Cloudflare::$plugin->api->purgeUrls($urls));
```

**Comment by thisanimus** [comment]
Ah, thanks:

```
Exceeded maximum amount of files that can be purged on a single request for your plan type.
```

Thanks for the quick response.

**Comment by bencroker** [comment]
Cloudflare enforces a limit of 30 URLs per purge request, so you’ll need to batch them if there are more than that. See how this is handled in Blitz here: https://github.com/putyourlightson/craft-blitz/blob/0074aca1ca1e3430f91a32f5f7a892baed3b0302/src/drivers/purgers/CloudflarePurger.php#L238-L244
