### ISSUE TITLE
Possible to purge associated URLS for entries that don't have a URL but are listed on the associated pages.

### ISSUE THREAD

**Issue by terryupton** [workingconcept/cloudflare-craft-plugin#71]
### Feature Request

A feature request as I don't believe this is currently possible.
At the moment you can setup Purge Rules - but this as I understand only purges urls and associated (right side) urls if the source entry has a URL. What I would like is the option to add Purge Rules that purge the associated (right side) urls even if they entry doesn't have a URL.

<img width="1402" alt="Screenshot 2024-05-21 at 12 16 29" src="https://github.com/putyourlightson/craft-cloudflare/assets/5698596/4f9e29f8-5ded-45a3-bc79-0700e424a208">

<img width="1652" alt="Screenshot 2024-05-21 at 12 16 43" src="https://github.com/putyourlightson/craft-cloudflare/assets/5698596/a2703d3d-df93-40d2-80a8-a1e57480b4b5">

My use case example is;

I have a section called 'Teams' but these team entries do not have their own URLS. Instead they are all listed via an entry query on a main Teams page. Therefore I would like to purge the main /teams page if any of the Teams entries are updated.

Here is the live example.
https://www.mkunitedfc.co.uk/teams

Each team card is an entry in a section called Teams.

Thanks
Terry

### Plugin Version

2.1.0

**Comment by bencroker** [comment]
You’re correct about the current limitation of that field and it only working for entries with URLs. How this functionality could be expanded to what you describe is unclear, however, and sounds beyond the scope of this plugin. 

To achieve more fine-grained caching strategies, [Blitz](https://putyourlightson.com/plugins/blitz) is your best bet, as it can handle this and a whole lot more without any configuration required.
