### ISSUE TITLE
[FR] Multi- domain/zone support

### ISSUE THREAD

**Issue by tibbis** [workingconcept/cloudflare-craft-plugin#73]
### Feature Request

From my understanding multi-domain purging is not supported yet as it requires multi-zone purging. 

### Plugin Version

3.0.1

**Comment by bencroker** [comment]
That’s right – this plugin only supports setting a single zone.

**Comment by tibbis** [comment]
This was a feature request

**Comment by bencroker** [comment]
Yes, what I meant to say is that this plugin is only intended to support a single zone, and there are no plans to extend this at present. If you need more fine-grained control over caching then please consider the [Blitz](https://putyourlightson.com/plugins/blitz) plugin.

**Comment by stephenmatthews** [comment]
Hey! We need multi-zone support too. Would you be open to accepting a PR if we could commit to doing this work? @bencroker

**Comment by bencroker** [comment]
Not at this time. Multi-zone support adds complexity and a maintenance burden. You’re welcome to fork the plugin and add the feature for your own use. I’d be happy to take a look at what you come up with and, at that point, consider whether this is something we’d be willing to include and support going forward.

**Comment by Michael-Paragonn** [comment]
FWIW, as another data point, we've got a large client that needs this as well.

**Comment by bencroker** [comment]
As noted above, multi-zone support is supported by the [Blitz](https://putyourlightson.com/plugins/blitz) plugin.

**Comment by bencroker** [comment]
Anyone still looking for this functionality is welcome to test PR https://github.com/putyourlightson/craft-cloudflare/pull/83 by @boboldehampsink.

Please report in the PR whether this satisfies your requirements, and if it does for enough people, I will consider merging it.

**Comment by bencroker** [comment]
Anyone?

**Comment by stephenmatthews** [comment]
Hi @bencroker - thanks for the update on this. We decided to build our own internal CF cache plugin because the craft-cloudlfare plugin didn't support multi-zone functionality at the time. I hope the new feature is implemented, as I'm sure many users with multi-site Craft installations will find it useful 😄

**Comment by boboldehampsink** [comment]
@stephenmatthews I would be interested in that plugin too
