### ISSUE TITLE
The Cloudflare Zone doesn't account for 'www' domains

### ISSUE THREAD

**Issue by paragonn** [workingconcept/cloudflare-craft-plugin#74]
### Bug Report

It appears that the zone check in the isPurgeableUrl function of the UrlHelper.php doesn't account for 'www' in the domain when comparing with the Cloudflare zone domain name.

In the /src/helpers/UrlHelper.php helper I changed (line 75):
  if (strtolower($urlDomain) !== strtolower($cfDomainName)) {

To this:
  if ( str_ends_with( strtolower($cfDomainName), strtolower($urlDomain) ) ) {

This will look to compare the base domain, so it will match with any subdomain not just domains with www.

### Plugin Version

3.0.1

### Craft CMS Version

5.5.5

### PHP Version

8.2

**Comment by bencroker** [comment]
Thanks for reporting this! Fixed in https://github.com/putyourlightson/craft-cloudflare/commit/c62211e95782d4c2081276bf4205a96283d4fb4a and released in [3.0.2](https://github.com/putyourlightson/craft-cloudflare/releases/tag/3.0.2).
