### ISSUE TITLE
Zones limited to 20 in zone list

### ISSUE THREAD

**Issue by uksitebuilder** [workingconcept/cloudflare-craft-plugin#8]
After adding API Key and email and verifying, only 20 zones are listed in the dropdown.

We have more than 20 zones in our account but cannot get the zone required as it is not listed

**Comment by mattstein** [comment]
Thanks for reporting this, @uksitebuilder! Would you mind trying out 2fe1b1ba75b68a6fcdc7367de9a4aef90ea302b4 and letting me know if that solves it for you? (I don't have an account with enough zones for a real-life test—but this should grab every zone you've got.)

**Comment by mattstein** [comment]
I just published v0.2.2 with this fix. Closing, but let me know if this _doesn't_ work for you @uksitebuilder!
