### ISSUE TITLE
Config file support

### ISSUE THREAD

**Issue by leigeber** [workingconcept/cloudflare-craft-plugin#9]
Hello and thanks for the great plugin.

Wondering if there's a way to define credentials in a config file or through aliases? I tried aliasing and that didn't go so well. We'd prefer to pull the values from our .env file. Thanks in advance!

**Comment by mattstein** [comment]
More flexible configuration seems like a sensible idea, @leigeber! I'll see what I can do.

**Comment by mattstein** [comment]
Hey @leigeber, I just updated [the project readme](https://github.com/workingconcept/cloudflare-craft-plugin/blob/master/readme.md) to include instructions for this. You can create `config/cloudflare.php` and add something like...

```php
<?php

return [
    'apiKey' => '',
    'email' => 'you@yourdomain.com',
    'zone' => '', // zone ID
    'purgeEntryUrls' => false,
    'purgeAssetUrls' => true,
];
```

...or similarly rely on environment variables with...

```php
<?php

return [
    'apiKey' => env('CLOUDFLARE_API_KEY'),
    'email' => env('CLOUDFLARE_EMAIL'),
    'zone' => env('CLOUDFLARE_ZONE_ID'), // zone ID
    'purgeEntryUrls' => env('CLOUDFLARE_PURGE_ENTRY_URLS', false),
    'purgeAssetUrls' => env('CLOUDFLARE_PURGE_ASSET_URLS', true),
];
```

...as long as you're defining them in your .env or elsewhere on your server. (The variables in the example are made up; they can be whatever you want as long as they're in `env('FOO')` format.)

Note that like all plugins, whatever you've got in the config file will persist even if you try to save new values from the control panel.

Closing this issue, but give me a shout if you run into any trouble!

**Comment by mattstein** [comment]
Bah, you're right @leigeber—thanks for catching that! Fixed in the readme and my earlier comment just in case somebody winds up here and copies my example.
